### ISSUE TITLE
Simplified view

### ISSUE THREAD

**Issue by pratyushpal** [theRoughCode/WatsMyMajorBeta#1]
Has the simplified view feature for the pre-requisite tree been implemented yet?
I toggled it and nothing changed.
- There are some minor UI bugs with text rendering. Ex: "Choose one of ... "

<img width="764" alt="screen shot 2018-07-16 at 1 38 30 am" src="https://user-images.githubusercontent.com/20086207/42744307-84dc7770-8899-11e8-9636-dae4c9ffd1a0.png">
<img width="999" alt="screen shot 2018-07-16 at 1 38 37 am" src="https://user-images.githubusercontent.com/20086207/42744308-84e982e4-8899-11e8-8d56-1c4c9b8209d1.png">

**Comment by theRoughCode** [comment]
Do you have anything in your courses?  The simplified view takes your current courses and figures out which branches aren't needed.

**Comment by pratyushpal** [comment]
Yeah, alright! It works well for me now. Thank you :D 👍

**Comment by clayton-halim** [comment]
You might want to add a tool tip or hint for that, I was confused as to what it did too
