### ISSUE TITLE
Toggling simplified view does nothing

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajorBeta#11]
Toggling simplified view while viewing the prerequisite tree of a course has no effect on the view.

**Comment by theRoughCode** [comment]
This view works when you have courses that are in the tree.  It would not make a difference to the tree if you have no courses.  Did you have courses when you clicked on the toggle?

**Comment by theRoughCode** [comment]
I've added a check to see if the user has taken any course in the tree.  If not, the "Simplified View" toggle would not show.  This might resolve future confusion.
