### ISSUE TITLE
Incorrect information - You've taken this course.

### ISSUE THREAD

**Issue by riyawalia** [theRoughCode/WatsMyMajorBeta#12]
<img width="410" alt="screen shot 2018-07-24 at 2 12 56 pm" src="https://user-images.githubusercontent.com/20255248/43157692-be18d5e8-8f4b-11e8-831a-703d7b70a6d0.png">
I haven't taken ENGL 336 yet or added it on quest. I think this appears for every course.

**Comment by theRoughCode** [comment]
Could you provide more information on how to replicate this? This bug isn't showing up for me.  Which courses did you have in your cart?

**Comment by theRoughCode** [comment]
Closing this due to stale issue.  Please reopen if it comes up again.
