### ISSUE TITLE
Error in the Major requirements feature.

### ISSUE THREAD

**Issue by pratyushpal** [theRoughCode/WatsMyMajorBeta#2]
- Error in the 3rd column of every major listed ( Computational Mathematics and AFM shown below)
- AFM had an error in its 5th column as well
<img width="1252" alt="screen shot 2018-07-16 at 1 58 08 am" src="https://user-images.githubusercontent.com/20086207/42744625-f5f2afd6-889b-11e8-9d3a-13f4e572c75c.png">
<img width="672" alt="screen shot 2018-07-16 at 1 59 47 am" src="https://user-images.githubusercontent.com/20086207/42744626-f600c1c0-889b-11e8-98b8-e276936f6a4a.png">

<img width="1268" alt="screen shot 2018-07-16 at 1 53 12 am" src="https://user-images.githubusercontent.com/20086207/42744523-37ac6440-889b-11e8-9d28-53a436e13328.png">

**Comment by theRoughCode** [comment]
Solved, thanks!
