### ISSUE TITLE
[My Courses] Dragging causes some weird highlights

### ISSUE THREAD

**Issue by 9at8** [theRoughCode/WatsMyMajorBeta#22]
![screenshot from 2018-07-25 15-54-17](https://user-images.githubusercontent.com/8235156/43224075-1b5578f6-9023-11e8-9abf-944a4e6ab454.png)
![screenshot from 2018-07-25 15-54-24](https://user-images.githubusercontent.com/8235156/43224076-1b702688-9023-11e8-90bd-44653083f8a3.png)

**Comment by theRoughCode** [comment]
Oh yea, those highlights are prerequisites of the dragged course.  I need to figure out a way to make it more obvious.  This is a build-up to a future feature of assisting a user of determining if a certain course is ok to be placed in a certain term.

**Comment by theRoughCode** [comment]
Closing this as this isn't a bug.
