### ISSUE TITLE
[My Courses] White background while dragging

### ISSUE THREAD

**Issue by 9at8** [theRoughCode/WatsMyMajorBeta#24]
When you drag a course to some other position in the same list, the white background behind the other courses stays there. It shouldn't.

No white background on original position:
![screenshot from 2018-07-25 16-01-50](https://user-images.githubusercontent.com/8235156/43224467-4b7fefc4-9024-11e8-8f3e-e1004265f0ec.png)

White background stuck on other course's previous location:
![screenshot from 2018-07-25 16-01-55](https://user-images.githubusercontent.com/8235156/43224468-4b9bd5b8-9024-11e8-92e2-7daf755c1353.png)

**Comment by theRoughCode** [comment]
Fixed, thanks!
