### ISSUE TITLE
Courses are gone Mr. Founder

### ISSUE THREAD

**Issue by MichLiang** [theRoughCode/WatsMyMajorBeta#3]
- Dragged a course from the bottom of the term to top and all the courses and terms disappeared uh oh
- Tried it with other courses, now moving any course from anywhere on the list to the top makes everything disappear
- Refreshing the page brought back everything

<img width="1081" alt="screen shot 2018-07-16 at 2 45 31 am" src="https://user-images.githubusercontent.com/37000837/42745897-27d2af68-88a3-11e8-9ae6-ebf416b9dd8e.png">

<img width="1082" alt="screen shot 2018-07-16 at 2 46 20 am" src="https://user-images.githubusercontent.com/37000837/42745890-1d3dcba0-88a3-11e8-91a7-ec7b41c08be0.png">

**Comment by theRoughCode** [comment]
Solved, thanks!
