### ISSUE TITLE
Course times not correct when displayed on schedule

### ISSUE THREAD

**Issue by seykafu** [theRoughCode/WatsMyMajorBeta#36]
<img width="831" alt="schedule 2 watsmymajor" src="https://user-images.githubusercontent.com/35230390/43985911-5cd0a216-9cd9-11e8-95f4-f4bbe4b90184.PNG">
<img width="544" alt="schedule watsmymajor" src="https://user-images.githubusercontent.com/35230390/43985912-5ce181b2-9cd9-11e8-822f-d722deb396f1.PNG">

**Comment by theRoughCode** [comment]
Fixed, thanks!
