### ISSUE TITLE
Undefined in coreqs

### ISSUE THREAD

**Issue by MichLiang** [theRoughCode/WatsMyMajorBeta#4]
<img width="952" alt="screen shot 2018-07-16 at 3 00 23 am" src="https://user-images.githubusercontent.com/37000837/42746142-683261e2-88a4-11e8-95af-40dadfaab322.png">
<img width="940" alt="screen shot 2018-07-16 at 3 00 42 am" src="https://user-images.githubusercontent.com/37000837/42746148-726881fa-88a4-11e8-800a-0278ce250d6f.png">
<img width="935" alt="screen shot 2018-07-16 at 3 01 20 am" src="https://user-images.githubusercontent.com/37000837/42746185-8af0f2ac-88a4-11e8-8041-ad60b0f3721b.png">

**Comment by theRoughCode** [comment]
Fixed undefined coreq error!
