### ISSUE TITLE
Courses cut off

### ISSUE THREAD

**Issue by MichLiang** [theRoughCode/WatsMyMajorBeta#7]
- Anything past 6 courses is cut off
- Can't scroll down, only to the side

<img width="977" alt="screen shot 2018-07-20 at 11 46 37 am" src="https://user-images.githubusercontent.com/37000837/43019670-9eba1068-8c12-11e8-8e8c-ad307a25dc7e.png">

**Comment by theRoughCode** [comment]
Fixed, thanks!
